small_sat_app/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'application#index'
  get 'small_sat/distributed_systems', to: 'small_sat#distributed_systems',
                                       path: 'small-sat/distributed-systems'
  get 'small_sat/about', to: 'small_sat#about',
                         path: 'small-sat/about'
  get 'small_sat/missions', to: 'small_sat#missions',
                            path: 'small-sat/missions'
  get 'small_sat/intersatellite_communications'
  get 'small_sat/design_parameters'
  get 'small_sat/signup', to: 'users#new', path: 'small-sat/signup'
  get 'small-sat/login', to: 'sessions#new'
  post 'small-sat/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, path: 'small-sat/users'
end

small_sat_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

small_sat_app/app/models/user.rb
# User model
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  PASSWORD_REGEX = /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]/
  validates :password, presence: true, length: { minimum: 8 },
                       format: { with: PASSWORD_REGEX }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCRYPT::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

small_sat_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def index
  end
end

small_sat_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log in the user and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

small_sat_app/app/controllers/small_sat_controller.rb
class SmallSatController < ApplicationController
  def distributed_systems
  end

  def missions
  end

  def intersatellite_communications
  end

  def design_parameters
  end

  def about
  end
end

small_sat_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Somewhere something INCREDIBLE is waiting to be known!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

small_sat_app/app/helpers/application_helper.rb
module ApplicationHelper
end

small_sat_app/app/helpers/home_helper.rb
module HomeHelper
end

small_sat_app/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

small_sat_app/app/helpers/small_sat_helper.rb
module SmallSatHelper
end

small_sat_app/app/helpers/users_helper.rb
# User helper
module UsersHelper
  # Returns gravatar for the given user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

small_sat_app/app/views/application/index.html.erb
<div class="center jumbotron">
  <h1>Technology Roadmap for Small Satellite Communications</h1>

  <p> Small satellite systems enable whole new class of missions for navigation,
    communications,  remotesensing  and  scientific  research  for  both
    civilian  and  military  purposes.   As  individual  spacecraft  are
    limited by the size,  mass and power constraints, mass-produced
    small satellites in large constellations or clusters could be useful in
    many science missions such as gravity mapping, tracking of forest fires,
    finding water resources, etc by providing improved  spatial  and  temporal
    resolution of the target. Future space missions  are  envisioned to become
    more complex and operate farther from Earth which will need to support
    autonomous operations with minimal human intervention, There will be a need to
    configure and maintain dynamic routes, manage intermediate nodes,
    and reconfigure themselves to achieve mission objectives. Hence,
    inter-satellite communication is a key aspect when satellites fly in formation.
    We present the various researches being conducted in the small satellite
    community for implementing inter-satellite communications based on the Open
    System Interconnection (OSI) model, in particular the various design
    parameters applicable to the first three layers of the OSI model,
    i.e., physical, data link and network layer. </p>

  <%= link_to "Sign up now!", '/small-sat/signup', class: "btn btn-lg btn-primary" %>
</div>

small_sat_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallSatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class='navbar navbar-fixed-top navbar-inverse'>
      <div class='container'>
        <nav>
          <ul class='nav navbar-nav navbar-left'>
            <li><%= link_to "About Small Satellites", '#' %></li>
          </ul>
        </nav>
        <nav>
          <ul class='nav navbar-nav navbar-right'>
            <% if logged_in? %>
            <li><%= link_to "Distributed Systems in Space", "/small-sat/distributed-systems" %></li>
            <li><%= link_to "Missions", '/small-sat/missions' %></li>
            <li><%= link_to "Inter-satellite Communications", '#' %></li>
            <li><%= link_to "Design Parameters", '#' %></li>
            <li><%= link_to "Users", '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          </ul>
          <% else %>
            <li><%= link_to "Log in", small_sat_login_path %></li>
          <% end %>
        </nav>
      </div>
    </header>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

small_sat_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

small_sat_app/app/views/small_sat/design_parameters.html.erb
<h1>SmallSat#design_parameters</h1>
<p>Find me in app/views/small_sat/design_parameters.html.erb</p>

small_sat_app/app/views/small_sat/distributed_systems.html.erb
<html>
<head>
<style type="text/css">
  html {
    scroll-behavior: smooth;
  }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
  $(function() {
    var $body = $('body');
    function animatedNavigation(link, tag) {
      $(link).click(function(e) {
        e.preventDefault();
        $body.animate({ scrollTop: $(tag).offset().top - 50 }, 1000);
      });
    }

    animatedNavigation('#flying-spacecraft-nav', '#formation-flying-spacecrafts');
    animatedNavigation('#flying-spacecraft-nav-1', '#satellite-constellation');
    animatedNavigation('#flying-spacecraft-nav-2', '#swarms');
    animatedNavigation('#flying-spacecraft-nav-3', '#fractionated-spacecraft');
  })
</script>
</head>
<body>
<div class="container">
  <div class="jumbotron">
    <h1>Distributed Systems in Space (DSS)</h1>
    <p>
      Multiple small spacecrafts provide higher efficiency gain by promoting
      adaptability, scalability, reconfigurability, and affordability compared to a
      single large satellite. When satellites fly in formation, it is required to
      maintain specific distance and orientation rela- tive to each other at
      specified altitudes. Depending on the formation characteristics, there can be
      two different approaches: ground based control and autonomous operations.
      In ground based control, formation flying satellites send the Global
      Navigation Satellite System (GNSS) measurements to the ground control center
      that provides necessary in- structions to maneuver into appropriate position
      in the formations. This approach is suit- able for formations with several
      kilometers of separation distance between the satellites. In autonomous
      formation flying, measurements are transmitted among the spacecrafts
      allowing the satellites to calculate the relative position in the
      formation, and Attitude and Orbit Control System (AOCS) is used to
      maneuver the satellite into appropriate positions. Autonomous approach
      is more difficult and riskier, and is suitable for missions that require
      tighter formations with frequent and autonomous adjustments of the
      relative positions.
    </p>
    <p>
      Small satellites with distributed computing capabilities can fly
      in various config- urations, for example, formation flying spacecraft,
      satellite constellation, swarms, and fractionated spacecraft.
      These multi-satellite configurations are new prototypes for
      inter-planetary explorations and remote sensing. Multi-satellite
      configurations are sub-sets of a more general class described as
      Distributed Space Systems (DSS) which fall in to four different categories:
      <ul style="list-style-type:disc">
        <li><a href="#formation-flying-spacecrafts" id="flying-spacecraft-nav">Formation flying spacecrafts</a></li>
        <li><a href="#satellite-constellation" id="flying-spacecraft-nav-1">Satellite Constellation</a></li>
        <li><a href="#swarms" id="flying-spacecraft-nav-2">Swarms</a></li>
        <li><a href="#fractionated-spacecraft" id="flying-spacecraft-nav-3">Fractionated spacecraft</a></li>
      </ul>
    </p>
    <a id="formation-flying-spacecrafts"><h2 text-align="left">Formation flying spacecrafts</h2></a>
    <p>In accordance with the engineering definition, for formation flying of
      spacecrafts, it is required to maintain relative separation, orientation
      or position among the space-crafts. The Leader-Follower (A-Train) is a
      good example of this pattern. In Leader-Follower pattern, multiple
      spacecrafts will be orbiting the Earth in the same orbit, separated from
      each other at a specific distance. The A-Train or Afternoon-Train
      initially consisted of eight U.S. and international Earth science
      satellites that fly approximately within seconds to minutes of each other
      to enable multiple science missions. As of June 2014, there are six
      active satellites namely, GCOM-W1 (SHIZUKU), Aqua, CloudSat, CALIPSO,
      Orbiting Carbon Observatory-2 (OCO-2) and Aura. The
      joint measure- ments provide an excellent sensor system for
      Earth observations.
    </p>
    <%= image_tag('Atrain.jpg', alt: "Atrain formation flying pattern", size: '500x400', class: "image_dss") %>
    <figcaption>Atrain formation flying pattern</figcaption>
    <a id="satellite-constellation"><h2 text-align="left">Satellite constellation</h2></a>
    <p>
      A satellite constellation is a set of similar or dissimilar satellites
      distributed in space so that they overlap well within the coverage area
      to accomplish mission objectives. A Cluster configuration is a subgroup
      of Constellation as it covers a smaller portion of the Earth. A Cluster
      consists of a number of satellites distributed in different orbital planes
      that operate cooperatively. The Flower constellation and TECHSAT-21 are
      examples of Cluster configuration.
    </p>
      <%= image_tag('cluster.jpg', alt: "Cluster formation flying pattern", size: '500x400', class: "image_dss") %>
      <figcaption>Cluster formation flying pattern</figcaption>
    <p>
      A satellite constellation is a more generalized configuration covering
      a larger portion of the Earth surface. There is no governing rules for
      inter-dependency for the satellites in a Constellation. The Global
      Positioning System (GPS) and IRIDIUM are examples of Constellation
      configuration. The IRIDIUM consists of 66 Low Earth Orbiting (LEO)
      satellites arranged in 6 orbital planes, with 11 satellites per plane,
      at an altitude of 780 km above the Earth surface. Figure below shows the
      Constellation configuration pattern for small satellites.
    </p>
    <%= image_tag('constellation.jpg', alt: "Constellation formation flying pattern", size: '500x400', class: "image_dss") %>
    <figcaption>Constellation formation flying pattern</figcaption>
    <a id="swarms"><h2 text-align="left">Swarms</h2></a>
    <p>
      A satellite swarm is defined as a self-organized, self-functioning
      satellites that communicate directly or indirectly that enables to
      achieve a common mission. It can be considered as a set of agents that
      take decisions independently without ground station intervention. It is
      highly autonomous with very high possibilities of reconfiguration or
      extension. The whole system is very complex and also requires precise
      navigational accuracy. The System F6, ”Future, Fast, Flexible,
      Fractionated Free-Flying”, project is an example of Swarms developed by
      the Defense Advanced Research Projects Agency (Darpa). The project aimed
      to replace traditional integrated satellites by clusters of smaller,
      cheaper, wirelessly-interconnected space modules that form a virtual
      satellite. System F6 intended to partition the functionalities performed
      by a large satellite (power, receivers, control modules, etc.) and assign
      each task to a dedicated micro-satellite. However, Darpa gave up on
      formation flying spacecraft concept in May, 2013. The Figure shows the
      artistic view of the System F6 project.
    </p>
    <%= image_tag('systemf6.jpg', alt: "Swarms", size: '500x400', class: "image_dss") %>
    <figcaption>Swarms: System F6 Project</figcaption>
    <a id="fractionated-spacecraft"><h2 text-align="left">Fractionated spacecraft</h2></a>
    <p>
      A fractionated spacecraft is a new architectural model, whereby the
      functionalities of a large satellite is distributed across a cluster of
      small satellites which are wirelessly interconnected. Each small satellite
      has different functionalities making the whole system heterogeneous.
      This configuration needs higher position and orbital control of the
      individual satellites with a moderate system design complexity. Such a
      system enhances robustness and flexibility in the architecture, while
      shortening development time and launch constraints.
    </p>
  </div>
</div>
</body>
</html>

small_sat_app/app/views/small_sat/intersatellite_communications.html.erb
<h1>SmallSat#intersatellite_communications</h1>
<p>Find me in app/views/small_sat/intersatellite_communications.html.erb</p>

small_sat_app/app/views/small_sat/missions.html.erb
<html>
<body>
  <div class="container">
    <div class="jumbotron">
      <p>In this section, we introduce a brief review of recent small satellite missions
      proposed or launched by several organizations and space agencies applying
      formation flying concepts. Table 2.2 shows some of the important multiple
      small satellite missions which are designed and developed by various space
      agencies and organizations.</p>
      <ul>
        <li>GRACE - The GRACE (Gravity Recovery and Climate Experiment) mission i
          s a joint venture of National Aeronautics and Space Administration (NASA)
          in the United States and Deutsche Forschungsanstalt fr Luft und Raumfahrt (DLR)
          in Germany which was launched in 2002. The system consists of two
          satellites, each of 480 kg, separated by 220 km in a polar orbit
          500 km above the Earth. The primary objective of the mission is to
          accurately map the variations in Earth’s magnetic field. The spacecrafts
          are still in operation and expected to continue through at least 2015. The
          telemetry tracking and command system is using S-band frequencies for
          uplink, downlink, and crosslink communications</li>
        <li></li>
        <li></li>
      </ul>

    </div>
  </div>
</body>
</html>

small_sat_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="jumbotron">
  <h1>Sign up</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

small_sat_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="jumbotron">
  <div class="row">
    <aside class="col-md-6">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  </div>
</div>